In [1]:
#Install the tensorflow module (not required in Google Colab, but is needed in your local PC)
!pip install tensorflow

In [2]:
#Here, we would go with the latest (2.x) release of tensorflow by selecting the version 
#Note: By default, Colab tends to use the 2.x version
%tensorflow_version 2.x 

In [4]:
#import the tensorflow module
import tensorflow as tf
#Display the tensorflow version we are using
print(tf.version)


<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [5]:
#The science (and art) of creating tensors
scalar_val = tf.Variable(123,tf.int16)
floating_val = tf.Variable(123.456,tf.float32)
string_val = tf.Variable("hello everyone. Nice to learn tensorflow!",tf.string)

In [6]:
#Let us display the values (print) these tensors
print(scalar_val)
print(floating_val)
print(string_val)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=123.456>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello everyone. Nice to learn tensorflow!'>


In [9]:
#The idea behind shape and rank of tensors
#Shape: Describes the dimension of the tensor (total elements contained along each dimension)

scalar_val_shap = tf.shape(scalar_val)
print(scalar_val_shap)

floating_val_shap = tf.shape(floating_val)
print(floating_val)

tf.Tensor([], shape=(0,), dtype=int32)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=123.456>


In [14]:
#Now, if we use e.g. lists/nested lists instead of just a "single" scalar value
list_tensor1 = tf.Variable([1,3,5,6],tf.int16)
print(list_tensor1)
print(tf.shape(list_tensor1))

list_tensor2 = tf.Variable([[1,2,3],[4,5,6]],tf.int16)
print(list_tensor2)
print(tf.shape(list_tensor2))

#how about the rank? It describes the level of nesting within the tensor in simple words.

print(tf.rank(list_tensor1))
print(tf.rank(list_tensor2))

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 3, 5, 6], dtype=int32)>
tf.Tensor([4], shape=(1,), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [24]:
#Reshaping tensors

reshaped_list_tensor2 = tf.reshape(list_tensor2,[6])
print(reshaped_list_tensor2)

list_tensor3 = tf.Variable([[1,2,3,1],[1,9,10,11],[1,5,11,22],[16,17,18,19]],tf.int16)
print(list_tensor3)
print(tf.rank(list_tensor3))
print(tf.shape(list_tensor3))

reshaped_list_tensor3 = tf.reshape(list_tensor3,[2,8,1])
print(reshaped_list_tensor3)
#or like this

reshaped_list_tensor3 = tf.reshape(list_tensor3,[8,2,1])
print(reshaped_list_tensor3)

#or automatically determine the shape by only giving one dimension!

reshaped_list_tensor3 = tf.reshape(list_tensor3,[1,-1])
print(reshaped_list_tensor3)


tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([4 4], shape=(2,), dtype=int32)
tf.Tensor(
[[[ 1]
  [ 2]
  [ 3]
  [ 1]
  [ 1]
  [ 9]
  [10]
  [11]]

 [[ 1]
  [ 5]
  [11]
  [22]
  [16]
  [17]
  [18]
  [19]]], shape=(2, 8, 1), dtype=int32)
tf.Tensor(
[[[ 1]
  [ 2]]

 [[ 3]
  [ 1]]

 [[ 1]
  [ 9]]

 [[10]
  [11]]

 [[ 1]
  [ 5]]

 [[11]
  [22]]

 [[16]
  [17]]

 [[18]
  [19]]], shape=(8, 2, 1), dtype=int32)
tf.Tensor([[ 1  2  3  1  1  9 10 11  1  5 11 22 16 17 18 19]], shape=(1, 16), dtype=int32)


In [31]:
#creating a tensor full of 1s (or 0s)
tensor_onefull = tf.ones([4,4,4,1])
print(tensor_onefull)

tensor_zerofull = tf.zeros([5,5])
print(tensor_zerofull)
#extracting specific values from tensors (similar to slicing in conventional programming)
tensor_sliced_onefull = tensor_onefull[0]
print(tensor_sliced_onefull)
tensor_sliced_zerofull = tensor_zerofull[0,1]
print(tensor_sliced_zerofull)

tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]], shape=(4, 4, 4, 1), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]], shape=(4, 4, 1), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


In [41]:
#another example from previously created tensor
print(list_tensor3)
tf_slicedexampleagain = list_tensor3[0,-2:]
print(tf_slicedexampleagain)

#selecting multiple rows
tf_slicedexampleagain = list_tensor3[1::]
print(tf_slicedexampleagain)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]], dtype=int32)>
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor(
[[ 1  9 10 11]
 [ 1  5 11 22]
 [16 17 18 19]], shape=(3, 4), dtype=int32)
